/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Enquiry = IDL.Record({
  'serviceRequired' : IDL.Text,
  'name' : IDL.Text,
  'company' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const EnquiryInput = IDL.Record({
  'serviceRequired' : IDL.Text,
  'name' : IDL.Text,
  'company' : IDL.Text,
  'details' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'submitEnquiry' : IDL.Func([EnquiryInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Enquiry = IDL.Record({
    'serviceRequired' : IDL.Text,
    'name' : IDL.Text,
    'company' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const EnquiryInput = IDL.Record({
    'serviceRequired' : IDL.Text,
    'name' : IDL.Text,
    'company' : IDL.Text,
    'details' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'submitEnquiry' : IDL.Func([EnquiryInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };